phoenixframework/phoenix_pubsub

test/support/cluster.ex
test/support/node_case.ex
test/test_helper.exs

Did this mainly as an exercise for myself... So no pressure if you don't want to accept this PR.  But I saw you mentioned something in irc about this earlier, and thought I'd share what this could look like. :)

Spawn slave nodes for clustered tests

---

lib/phoenix_pubsub/gc.ex
lib/phoenix_pubsub/local.ex
lib/phoenix_pubsub/pubsub.ex
lib/phoenix_pubsub/tracker.ex
test/phoenix_pubsub/local_test.exs
test/phoenix_pubsub/tracker_test.exs
test/shared/pubsub_test.exs
test/support/node_case.ex

@josevalim I imagine you'll want to chat about this one. The subscriber is responsible for calling :subscribe/:unsubscribe only if they have a new topic to subscribe to or an existing one to unsubscribe from. For 1M subscribers on my laptop, subscription lookup time is ~ 50 microsecs, so it's not too costly and the lookup happens in the caller's context. The only work added to the local server is keeping tracking of the monitor refs and subscription counts, but it should be minimal. Thoughts?

Fix monitor leak

---

README.md
config/test.exs
test/phoenix_pubsub/pg2_test.exs
test/phoenix_pubsub/tracker_test.exs
test/support/cluster.ex

The code, docs, and some tests contain references to a master/slave replication configuration.
While this terminology has been used for a long time, those terms may carry racially charged meanings to users.
This patch replaces all occurrences of master and slave with 'primary' and 'replica', following the Django Project's lead.
@see: https://github.com/django/django/pull/2692 and https://github.com/django/django/pull/2694
N.B. - there are two private functions in `tests/` where the slave terminology is still used, because they are calling erlang directly. This should be the exception and not the rule.

Replace occurances of "master/slave" terminology with "primary/replica"

---

lib/mix/tasks/phoenix.pub_sub.bench.ex
lib/phoenix_pubsub/tracker.ex
lib/phoenix_pubsub/tracker/delta_generation.ex
lib/phoenix_pubsub/tracker/replica.ex
lib/phoenix_pubsub/tracker/state.ex
test/phoenix_pubsub/tracker/delta_generation_test.exs
test/phoenix_pubsub/tracker_state_test.exs

Add pids table for reverse lookup against
values table for efficient matching of
get_by_pid.
Optimize ets select for get_by_topic
by or'ing downed node comparisons.

Optimize lookups with ets pids table

---

lib/phoenix_pubsub/pg2.ex
test/phoenix_pubsub/pg2_test.exs

Maybe there is a better way to do the test than checking that the last shard subscriber count?

Set default pool size to number of schedulers

---

lib/phoenix_pubsub/tracker.ex

I think that's a leftover from changing from `make_ref()` to `:crypto.strong_rand_bytes(8)` in 31a68a2c.

No need to encode the random bytes in Erlang's external term format

---

tasks/phoenix.pub_sub.bench.exs

On latest Elixir master with xref:
```
==> phoenix_pubsub
Compiling 13 files (.ex)
warning: function :none.exception/1 is undefined (module :none is not available)
lib/mix/tasks/phoenix.pub_sub.bench.ex:57
Generated phoenix_pubsub app
```

Fix xref warning for `Mix.Tasks.Phoenix.PubSub.Bench`

---

lib/phoenix/tracker.ex

Was getting errors trying to use example code from [Implementing a Tracker](https://hexdocs.pm/phoenix_pubsub/Phoenix.Tracker.html#implementing-a-tracker): `(UndefinedFunctionError) undefined function Phoenix.PubSub.direct_broadcast/3`
Fixed by using code from test example here:
https://github.com/phoenixframework/phoenix_pubsub/blob/0190f26ca5a83eea1ac8f6f6c017be6cc98859ef/test/support/node_case.ex#L34

Quick fix for "Implementing a Tracker" example

---

README.md

This simply adjusts the markdown so that the code snippets are highlighted.

Syntax highlighting in Readme

---

lib/phoenix/tracker.ex
test/phoenix/tracker/integration_test.exs

Hey! 
First of all, thank you for your great work! Phoenix and its Channel/Presence capabilities are absolutely cool and they give a lot of fun for developing web applications again!
I've opened this Pull Request as I couldn't find proper way of doing this. Please, consider following:
```elixir
Presence.track(socket, socket.assigns.user_id, %{browser: "Chrome", status: "online"})
```
which is similar to what's described in video from this great blog post: [What makes Phoenix Presence special, and a sneak peek](https://dockyard.com/blog/2016/03/25/what-makes-phoenix-presence-special-sneak-peek).
There is a way of updating _current_meta_ with [`Phoenix.Tracker.update/5`](https://github.com/phoenixframework/phoenix_pubsub/blob/master/lib/phoenix/tracker.ex#L178), but it expects _full `meta`_ …

Allow partially updating `meta`

---

lib/phoenix/pubsub.ex

A very small change aimed at improving the consistency of the documentation in the Direct usage section of the Phoenix.PubSub module.
The first code snippet in the section shows how to create a new PubSub instance and give it a name, but the second snippet uses a different name to demonstrate subcribing and broadcasting.  This change uses the PubSub instance's name consistently in both code samples.

Trivial Documentation Change

---

lib/phoenix/pubsub.ex

Small addition for `direct_broadcast` documentation. This also makes the example in the tracker doc functional.

Fix documentation on direct_broadcast

---

lib/phoenix/tracker.ex
lib/phoenix/tracker/delta_generation.ex
lib/phoenix/tracker/state.ex
test/phoenix/tracker/delta_generation_test.exs

Zombie pids could reappear in cases where a delta generation
was sent to catch-up a replica containing a previously perm-downed
version of that replica. Properly prune delta generations to prevent
this.
// @Gazler @gabiz This should be fixed on this PR. Please verify this branch against your setup. Thanks!

Prune perm-downed replicas from delta generations to fix zombie pids

---

lib/phoenix/tracker.ex

The tracker implementation is supposed to return `{:ok, state}` and not `{:ok, pid}`.
This change fixes dialyzer warnings in my own project that uses phoenix_pubsub.

Fixed type for Tracker.init callback

---

lib/phoenix/pubsub/pg2.ex

Infinitesimal commit for a typo that I just noticed.

Fix typo in Phoenix.PubSub.PG2 docs for :pool_size option

---

lib/phoenix/tracker.ex
lib/phoenix/tracker/delta_generation.ex
lib/phoenix/tracker/state.ex
test/phoenix/tracker/delta_generation_test.exs
test/phoenix/tracker/integration_test.exs
test/phoenix/tracker/state_test.exs
test/support/node_case.ex

@gazler this includes the test cases from your branch that re-create the ghosting issues. I've changed the way replication is done to only extract and transfer presences within the remote node's context, so we avoid replicating presences that may be raced in a permdown. Everything looks good on my end with my own applications. Can you run it through its paces locally and verify on your end with the scenarios you've done preivously? Thanks!
Chris

Fix presence ghosting

---

lib/phoenix/pubsub/local.ex
test/support/node_case.ex

Do not use `Task.async` and `wait` when calling `do_broadcast` on pubsub pool shards.
The supporting documentation & rationale is supplied with #78, which should be ignored in favor of this PR.

do_broadcast loops over pubsub shards without spawning Tasks

---

lib/phoenix/pubsub.ex

Avoid a deprecation warning when copy pasting from the documentation

Update subscription documentation to not require pid

---

tasks/phoenix.pub_sub.bench.exs

Hi.
I found there is some error when I tried to run `mix phoenix.pub_sub.bench`. 
```
** (UndefinedFunctionError) function Phoenix.Tracker.State.extract/1 is undefined or private. Did you mean one of:
* extract/3
```
After changing some code, it works. But I'm not sure is it correct.

fix `phoenix.pub_sub.bench.exs`

---

lib/phoenix/pubsub.ex
lib/phoenix/pubsub/pg2.ex

This PR fixes a couple of documentation typos.

Fix doc typos in Phoenix.PubSub and Phoenix.PubSub.PG2

---

lib/phoenix/pubsub/pg2.ex
test/phoenix/pubsub/pg2_test.exs

This should fix errors when starting the PG2 PubSub through:
```ex
children = [
{Phoenix.PubSub.PG2, name: MyApp.PubSub},
...
]
```
with resulting:
```
** (Mix) Could not start application MyApp: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: Phoenix.PubSub.PG2
** (EXIT) an exception was raised:
** (FunctionClauseError) no function clause matching in Phoenix.PubSub.PG2.start_link/1
(phoenix_pubsub) lib/phoenix/pubsub/pg2.ex:45: Phoenix.PubSub.PG2.start_link({:name, MyApp.PubSub})
(stdlib) supervisor.erl:365: :supervisor.do_start_child/2
(stdlib) supervisor.erl:348: :supervisor.start_children/3
(stdlib) supervisor.erl:314: :supervisor.init_children/2
(stdlib) gen_server.erl:365: :gen_server.init_it/2
(stdlib) gen_server.erl:333: …
```

Fix the child_spec for PG2: the start tuple needs the arguments to be a list

---

lib/phoenix/tracker/replica.ex

Elixir 1.7.0 requires the use of singular non-underscored time units.
Included in this commit:
https://github.com/elixir-lang/elixir/commit/94f3d60a262c1ca11547fd0f7395d2875faa261e

Fix deprecation warnings on Elixir 1.7.0

---

lib/phoenix/tracker.ex
lib/phoenix/tracker/delta_generation.ex
lib/phoenix/tracker/replica.ex
lib/phoenix/tracker/state.ex
mix.lock

After running Dialyzer on Elixir 1.4/OTP 20 with `--unknown` flag,
39 warnings have been emitted. This commit fixes all those warnings,
although it required introducing private type `Tracker.state`.

Fix Dialyzer warnings

---

lib/phoenix/tracker.ex

Since v1.1.0 the example `MyTracker` implementation given in the `Phoenix.Tracker` module docs does not work. When you attempt to start the `MyTracker` process an error is returned:
```console
iex> Phoenix.PubSub.PG2.start_link(name: MyPubSub)
{:ok, #PID<0.211.0>}
iex> MyTracker.start_link(pubsub_server: MyPubSub)
** (EXIT from #PID<0.176.0>) shell process exited with reason: an exception was raised:
** (FunctionClauseError) no function clause matching in Phoenix.Tracker.init/1
(phoenix_pubsub) lib/phoenix/tracker.ex:260: Phoenix.Tracker.init([MyTracker, [name: MyTracker, pubsub_server: MyPubSub], [name: MyTracker, pubsub_server: MyPubSub]])
(stdlib) gen_server.erl:374: :gen_server.init_it/2
(stdlib) gen_server.erl:342: :gen_server.init_it/6
(stdlib) proc_lib.erl:249: …
```

Fix `Phoenix.Tracker` example implementation in module docs

---

lib/phoenix/tracker/clock.ex
lib/phoenix/tracker/delta_generation.ex
lib/phoenix/tracker/state.ex
test/phoenix/tracker/clock_test.exs
test/phoenix/tracker/delta_generation_test.exs
test/phoenix/tracker/state_test.exs

This is done on top of #108 and #109.
This PR is an attempt to fix issues discovered by the property based tests that can generate split and join network between certain nodes:
1. [This counterexample](https://github.com/distributed-owls/breaking-pp/blob/master/test/large/cluster_counterexamples_test.exs#L66-L95) reproduced a case when joins are propagated via netsplit (node 1 stores information about sessions connected to node 3 internally), but leaves are not -- when the node 3 sessions are disconnected and the split is healed, these sessions still appear to be connected on node 1.
The proposed solution makes the filter in `observe_removes` less strict. I'm not sure what performance implications this might have, though.
2. [This …

Improve replication over netsplit

---

lib/phoenix/pubsub.ex

Use `Process.info(self(), :messages)` instead of `Process.info(self())[:messages]`.
The later one was returning an empty array for me every time.
Issue appeared with Phoenix PubSub 1.1.1, Elixir 1.7.4, Erlang/OTP 21 [erts-10.1.1]

Fix documentation (DocTest) for Phoenix.PubSub

---

lib/phoenix/tracker/shard.ex

This is called each time there's a join or other kind of update.
This is based on elixir plug [request id][1].
[1]: https://github.com/elixir-plug/plug/issues/629

Improve random_ref() function performance

---

lib/phoenix/pubsub/adapter.ex

This ensures they are named in exdoc, being called `node_name` instead
of `arg2`, etc.

docs(Adapter): include variable names in callbacks

---

lib/phoenix/pubsub/pg2.ex

Pubsub v2.0 expects there to be a single process for the process group
named `Elixir.my_pubsub.Adapter`.
v2.1 added pools, which means that the processes are supervised with a
supervisor called `Elixir.my_pubsub.Adapter` along with n processes
named `Elixir.my_pubsub.Adapter_n` where n is the pool size.
This commit changes the supervisor name to
`Elixir.my_pubsub.Adapter_supervisor`
and renames pool item 1 to be `Elixir.my_pubsub.Adapter`. This will
allow backwards compatability with v2.0 when the pool size is set to 1.

Rename first adapter in the pool for backwards compatability

---

lib/phoenix/pubsub.ex

Presently, it is not clear that `broadcast_from` sends to all but the sending process.  Update the docs to make it clear.

update [local_]broadcast_from docs

---

lib/phoenix/tracker/shard.ex
lib/phoenix/tracker/state.ex
test/phoenix/tracker/state_test.exs

Tracker update is handled as leave + join and ETS updates are applied in this notion, that is, a delete followed by an insert. Since tracker lookup reads ETS on the caller side, it can happen concurrently to tracker update, so there is a race condition when the ETS read happens between said delete and insert.
The "values" ETS table (which keeps the metadata) is an :ordered_set, which means that we can do an atomic update just by inserting the new value, without prior delete. So I made two changes:
* for the local case I added `State.leave_join`, which works just like `State.leave` + `State.join`, but without the unnecessary delete
* for the remote case I updated `State.merge` to gather desired inserts/deletes to ETS, do a simple diff and only then apply the changes (which makes an entry …

Update ETS atomically on tracker update

---

lib/phoenix/tracker/state.ex

Closes https://github.com/phoenixframework/phoenix_pubsub/issues/175.

Fix leftover entries after distributed tracker update

---

test/support/cluster.ex

This module has been helpful to me as a guide for writing similar distributed test helpers in several projects, but I've run into issues related to `epmd` not running in the past and forgotten that was the problem/solution. Maybe I'm not alone? Either way, a helpful moduledoc would prevent that in the future!

Add helpful moduledoc to Phoenix.PubSub.Cluster

---

CHANGELOG.md
lib/phoenix/tracker.ex
lib/phoenix/tracker/shutdown_handler.ex

Add ability to replicate state immediately during normal shutdown via new option

Add ability to replicate state immediately during normal shutdown

---

lib/phoenix/tracker.ex

Fixes https://github.com/phoenixframework/phoenix_pubsub/issues/194
This ensures the Supervisor doesn't restart Shards that we're trying to shut down using `Phoenix.Tracker.graceful_permdown/1`

Only restart shards if they terminate unexpectedly

---

lib/phoenix/tracker/shard.ex

The changes fix the following dialyzer warning:
```
lib/phoenix/tracker/shard.ex:409:38:unknown_type
Unknown type: Phoenix.Tracker.State.replica_name/0.
```
According to the functions flow, `clockset_replicas` returns `[State.name]`
https://github.com/phoenixframework/phoenix_pubsub/blob/main/lib/phoenix/tracker/clock.ex#L11-L11

Fix dialyzer Shard module warning
